package Konzentration;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.*;
/**
 *
 * @author kilian
 */
public class test extends javax.swing.JFrame {
    ArrayList<JButton> Buttons = new ArrayList<>();
    int zaehler = 0;
    JLabel textZurButtonAuswahl;
    /**
     * Creates new form testFrame
     */
 
    public test() {
       
        
        initComponents();
        persoenlichesInitComponents();

           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        
  
    private void persoenlichesInitComponents(){
        setTitle("Endlich wieder java!");
        getContentPane().setBackground(Color.red);
        
        // 20 Knöpfe werden erzeugt und der Arraylist hinzugefügt.
        for (int index=0; index<20; index++){
            JButton meinKnopf = new JButton();
            meinKnopf.setText("");
            meinKnopf.setFont(new java.awt.Font("Lucida Grande", 0, 22));
            meinKnopf.setBounds(20+60*(index%5), 20+60*(int)(index/5), 50, 50);
            getContentPane().add(meinKnopf);
            meinKnopf.addActionListener((java.awt.event.ActionEvent evt) -> {
                meinKnopfActionPerformed(evt);
            });
            Buttons.add(meinKnopf);
        }
        
        // und ein Label
        textZurButtonAuswahl = new JLabel();
        textZurButtonAuswahl.setBounds(20, 260, 300, 20);
        textZurButtonAuswahl.setFont(new java.awt.Font("Lucida Grande", 0, 14));
        getContentPane().add(textZurButtonAuswahl);
    }
    
    
    private void meinKnopfActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        zaehler++;
        textZurButtonAuswahl.setText("Zum "+zaehler+". Mal gedrückt! Und zwar Knopf " + Buttons.indexOf(evt.getSource()));
        
        anzeigen();
        
    } 
   
   /**
    * Hier soll die Anzeige aufgefrischt werden!
    */
   public void anzeigen(){
      
   }
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewControler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewControler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewControler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewControler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewControler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
